### ISSUE TITLE
Rust Backend indexer slow

### ISSUE THREAD

**Issue by codeforfunzz** [Concordium/concordium-scan#279]
Hi
I'm glad when saw your team develop new explorer,  but when I tried Rust version, it's slower than .Net version so much

**Comment by limemloh** [comment]
Hi @codeforfunzz 
Thank you for showing interest.

For this issue to become helpful, we need a bit more detail here:

1. What do you experience is slow? 
    The indexing? If so, which network are you running against? 
    Or is it the GraphQL API calls? If so, which queries are you testing?
2. How did you build the service?
3. How are you running the service? Is the Concordium node running locally? Is the PostgreSQL database running locally? What are the specs?

Also, the new backend is still under development and doing benchmarks, at the current state, does not make a lot of sense. It does not cover the old API yet. When the backend covers more, we will index testnet and mainnet and start optimizing database queries based on benchmarks.

Personally, I doubt the change in language itself will make a huge difference in performance, since the service is mostly just transferring data between Concordium node and the database, or the database and the user.
Optimizing the database will make the difference.

**Comment by codeforfunzz** [comment]
Hi, 
I tested the indexer in mainnet, the node run locally.
Anyway, really hope new version explorer coming soon, you can research Blockscout for UI idea. I think a good explorer will help the ecosystem so much.

**Comment by limemloh** [comment]
I agree.
First time around we are replacing the backend with minimal frontend changes, how the project evolves from there is still being debated, but we do have several things that we want to improve.
If you have specific features or ideas for this project, please open an issue with a description.

I'll close this issue for now.
