### ISSUE TITLE
Change to total circulating supply, New Endpoint

### ISSUE THREAD

**Issue by coolmagic** [Concordium/concordium-scan#53]
There is a need of some changes in handling circulating supply and additional endpoint for Coinmarketcap and Coingeko consumption. Explanation as follows:

![image.png](https://images.zenhubusercontent.com/634fc3bd5337c0378ee8cf86/e2d4ca7e-6ac5-455d-80a9-3b1063258785)

 1. change the header from "Total circulating supply of CCD" to "Total unlocked CCD"
2.  We need a new data point on CCDScan.io and more importantly an additional API endpoint.
     It should show numbers = "Total supply of CCD minus 6 specific wallets" AND it should include punctuation, for example: 6836607809.123456.
Perhaps it would make sense to make two version of it. One with punctuation and one without?

Here are the accounts that are NOT circulating:
3ofwYFAkgV59BsHqzmiWyRmmKRB5ZzrPfbmx5nup24cE53jNX5
4MPJybKC9Kz7kw9KNyLHhuAEt4ZTxLsd3DBDbxtKdUiv4fXqVN
44bxoGippBqpgseaiYPFnYgi5J5q58bQKfpQFeGbY9DHmDPD78
4d13WVDNKVGDUxRUb1PRQAJyTwWSVcjWS7uwZ1oqmDm5icQEPT
3EctbG8WaQkTqZb1NTJPAFnqmuhvW62pQbywvqb9VeyqaFZdzN
47xTHwtFra1d4Mq4DYZuZYJEYrDXY34C4CGkTTzT6eiwjEczuT

Step 1. Build the new endpoint
Step 2. Get Coin Market Cap to Access it
Step 3. Update CCDScan UI with the third data point
Step 4. Get Coin Geko to consume it.

**Comment by parv0888** [comment]
We have raised the PR but it has some issues. Please do explain the following questions
1. _Change the header from "Total circulating supply of CCD" to "Total unlocked CCD"_ : Is this a change in just the Header Language or does it represent any change in the actual calculation / value displayed?
2. _We need a new data point on CCDScan.io_ : Is this the same data point that we are discussing in point 1 _Total unlocked CCD_ Or 
The calculations mentioned here _Total supply of CCD minus 6 specific wallets_ does not represent _Total unlocked CCD_
3. In the Point 2 in the calculation mentioned _Total supply of CCD minus 6 specific wallets_ what does the term "Total Supply" mean? Is it the **Total Released Supply** Or **Total Circulation Supply** (being renamed to _Total unlocked CCD_)?

As per our understanding of the Concordium Blockchain and tokenomics mentioned [here](https://concordium.com/tokenomics/). The PR currently makes the following assumptions
1. _Total unlocked CCD_ = Total Released CCD (Which is calculated based on [hard coded values](https://github.com/Concordium/concordium-scan/blob/c7c9b372852dbff828110de3550089fb636921e1/backend/Application/Api/GraphQL/Import/InitialTokenReleaseScheduleRepository.cs#L21)) - Balance of 6 Accounts
2. The API endpoint created returns the value calculated in point 1 (Total unlocked CCD). 
3. The Data point added to the Home Screen also shows the same value with decimals. Which is currently named **Total Circulation Supply** and is renamed to  **Total unlocked CCD**

However these calculation are erroneous because as per the [release schedule](https://github.com/Concordium/concordium-scan/blob/c7c9b372852dbff828110de3550089fb636921e1/backend/Application/Api/GraphQL/Import/InitialTokenReleaseScheduleRepository.cs#L21) On 2022/JAN/05, 230008706939004 Micro CCDS are released but the total balance of Non Circulating Accounts is greater than 230008706939004 by a large margin forcing the system to calculate a negative value for _Total unlocked CCD_

**Comment by MikaelConcordium** [comment]
The goal is to have three numbers:

Total CCD in existance: No change (this is also referred to in the above text as just "total supply".
Total Unlocked CCD: No change to the number, but the header text should be changed from "Total circulating supply of CCD" into "Total unlocked supply of CCD".
Total Circulating Supply: This is the new number we are looking to release. It should be equal to the "Total CCC in existance" minus the 6 account.

**Comment by chrmatt** [comment]
With the new definition of circulating supply, we consider locked tokens on other accounts than those six to be circulating. That seems pretty weird. Is it intentional?

**Comment by coolmagic** [comment]
**** Please **do not deploy** this PR changes yet.
@MikaelConcordium needs to get some clarifications around this from management.

**Comment by MikaelConcordium** [comment]
We are good to go.

**Comment by mh-concordium** [comment]
_Total circulating supply of CCD_ label was not changed to _Total Unlocked CCD_.
![image.png](https://images.zenhubusercontent.com/6284893f971a3daf4db6e569/4b178239-433b-47d3-9250-f91abced4fdf)

**Comment by abizjak** [comment]
@parv0888 can you please make a PR from main fixing the text as agreed above?

**Comment by abizjak** [comment]
@parv0888 There was confusion about this due to many confusing messages as to what should be done.

As it is not it looks like what was agreed to in those messages. I'm a bit worried about you saying "probably because this is not mainnet". I expected that you would know for certain whether the unlocked field is not present because there is no release schedule or not.

**Comment by parv0888** [comment]
> I can see there is a bad typo, it says "as it is not" instead of "as it is now". So just to confirm, I do think what is implemented now is what was agreed.
> 
> The second part of the message, I expressed concern about your phrasing with saying "probably". I would expect you would know for certain.
> 
> So it seems good, but we'll verify of course on mainnet once catchup is complete.

thanks

**Comment by mh-concordium** [comment]
After discussing with @MikaelConcordium, it has been concluded that it is necessary to add seventh account to the above list of six. 

Please add account address 4LH62AZmugKXFA2xXZhpoNbt2fFhAn8182kdHgxCu8cyiZGo2c
@Thahara could you please just verify that this is correct address.

**Comment by Thahara** [comment]
Yep, at least that is the account that receives foundation rewards according to ccdscan

**Comment by schwartz-concordium** [comment]
Consulted @Thahara  and @mh-concordium and confirmed it can be closed.
