### ISSUE TITLE
What does Rec. length represent?

### ISSUE THREAD

**Issue by mh-concordium** [Concordium/concordium-scan#81]
**Bug Description**
It is not really clear what the value Rec.length represents?

Looking at the number and comparing it to numbers on https://dashboard.mainnet.concordium.software/  this is is not last block received, neither last finalized, neither number of messages sent/received

**Steps to Reproduce**
Follow the link https://ccdscan.io/nodes and look at Rec.length column.

**Expected Result**
I assume, we first have to clarify what is it that this number represents.

**Actual Result**
Maybe a tooltip that explains what the value is.

**Versions**
- Software Version: version 0.1.2/1.0.2

**Comment by schwartz-concordium** [comment]
Hi @mh-concordium 

`Rec.lenght` maps to `blocksReceivedCount` from the endpoint `https://dashboard.mainnet.concordium.software/nodesSummary`.

 It is the number of blocks received by the node since the node was last restarted.
https://github.com/Concordium/concordium-grpc-api/blob/66132bca3f9f3df71fecfda3b4cf52f9a7134f65/v2/concordium/types.proto#L1925

I have done some smoke testing and validated those numbers from the endpoint are the same as those seen in the CCD scan.

Regarding the next steps from here, I would agree it we probably could use the column space better and show something which could more insights for the node runner. I have made a improvement task for this in Jira https://concordium.atlassian.net/browse/CBW-1542.

Due to a task has been created in Jira and an answer has been given describing what the column represent I will close this issue. Thanks for spending the time making the issue in the first place :-)

If you still find some action missing please do not hesitate to reopen.
